"""Add status to Client

Revision ID: 08db3395556d
Revises: 
Create Date: 2024-07-07 12:38:04.708691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08db3395556d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
