"""Add timestamps to Task model

Revision ID: 84570d106ad0
Revises: 9c4b39574232
Create Date: 2024-07-07 14:34:18.386461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84570d106ad0'
down_revision = '9c4b39574232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('in_progress_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('task_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('deadline',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('completion_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('completion_link',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completion_link',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('completion_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('deadline',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('task_description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('in_progress_time')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
